server:
  port: 8081

spring:
  application:
    name: Product-Service
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/product_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

